### PR TITLE
Name clash demo

### PR DESCRIPTION
**Pull request by vgrichina**
Triggers AssemblyScript#429

### CODE REVIEW

**Comment by vgrichina** [comment]
To reproduce run `./test.sh` in `tests/near-bindgen`

**Comment by dcodeIO** [comment]
`./test.sh` fails with `ERROR: Import file 'json/encoder.ts' not found.` for me. Anything I need to set up first?

**Comment by MaxGraey** [comment]
@vgrichina It hard to investigate to this issue with bunch of generated code. It will be great if you reproduce this with minimal example ideally already pregenerated and in original fork

**Comment by vgrichina** [comment]
> `./test.sh` fails with `ERROR: Import file 'json/encoder.ts' not found.` for me. Anything I need to set up first?

@dcodeIO  `npm install` in root should likely help

**Comment by vgrichina** [comment]
@MaxGraey did you try to have class with same name in 2 modules (one of them including another)? 
Do you have example of that which compiles without problem?

**Comment by dcodeIO** [comment]
Yeah, tried `npm install`, but seems it still can't find the `assemblyscript-json` module. Is that on npm or so actually?

**Comment by vgrichina** [comment]
@dcodeIO it's on GitHub.

Am I doing `package.json` wrong?
`    "assemblyscript-json": "github:nearprotocol/assemblyscript-json",`

**Comment by dcodeIO** [comment]
Doesn't seem so, it's actually in `node_modules`. The exact error I see is:

```sh
$ ./test.sh
+ BASEDIR=../..
+ ../../bin/asc model.ts --nearFile model_near.ts
+ ../../bin/asc main.ts --nearFile main_near.ts
ERROR: Import file 'json/encoder.ts' not found.
    at parseBacklog (xyz\assemblyscript\cli\asc.js:355:25)
```

**Comment by vgrichina** [comment]
@dcodeIO I guess symlinks don't work in Git? 
I have symlink pointing json -> ../../node_modules/assemblyscript-json/assembly

**Comment by dcodeIO** [comment]
That might be the issue, I'm on Windows

**Comment by vgrichina** [comment]
@dcodeIO got it, then it should be enough just to copy files from `../../node_modules/assemblyscript-json/assembly` folder to `json` folder.

**Pull request closed without merging**
