### PR TITLE
Merge with Upstream and Simplify Decoding

### PR DESCRIPTION
**Pull request by willemneal**
- Decreases binaries by ~50% by defining fewer classes
- Handle Type Aliases
- Fixes stub allocation
- Loader much faster at accessing typed arrays 
- Fixes typing generation

### CODE REVIEW

**Comment by willemneal** [comment]
It fails the tests because the new loader changed APIs.

**Comment by vgrichina** [comment]
@willemneal LGTM, but let's create demo fiddle on studio (overriding compiler in setup.js) to make sure this works

**Comment by willemneal** [comment]
Okay I'll make one now.  Could we set this up to use the render bot?

**Comment by willemneal** [comment]
https://near-studio-staging-pr-154.onrender.com/?f=zftjgvt4y&asc=11cc59325e5bae30589cf4da9fdbfbe2e14b09b1

This uses the new URL asc parameter from https://github.com/nearprotocol/NEARStudio/pull/154

But here is this commit on the live site: https://studio.nearprotocol.com/?f=p8h1iu1hq

**Comment by bowenwang1996** [comment]
Do you mind pulling the latest upstream again? The resolver fix would be quite useful.

**Comment by janedegtiareva** [comment]
Do you mind merging master so that we can easily see results of vm tests?

**Comment by willemneal** [comment]
Sure just updating merging with upstream and there were some issues introduced by the second to last PR so I'm going to merge the one before it.

**Comment by bowenwang1996** [comment]
What was the issue?

**Comment by willemneal** [comment]
Not exactly sure.  The errors are internal to bignum and it no longer likes the way I handled `u128` as a special case.  I tried rolling back to just the PR with type resolution and I get the same thing.  I'm now trying the PR before to see if it is what introduces this error.

**Comment by willemneal** [comment]
So I narrowed down the error from the type resolution PR to bignum.  I just created a PR there: https://github.com/MaxGraey/bignum.wasm/pull/27 to fix it.  For now I just merged with the PR before it and we can return after bignum is fixed.

**Comment by willemneal** [comment]
@vgrichina I also changed the API so that `obj.encode()` returns a `Uint8Array` and so does `encode<Obj>(obj)`.

**Pull request merged**
